// @generated by scripts/generate-tokens.js from Figma — DO NOT EDIT
import SwiftUI

// MARK: - Theme.Typography — Text styles from Figma

extension Theme {
    enum Typography {
        static let display = Font.custom("Inter-Bold", size: 54)
        static let h1 = Font.custom("Inter-Bold", size: 44)
        static let h2 = Font.custom("Inter-Bold", size: 32)
        static let h3 = Font.custom("Inter-Bold", size: 24)
        static let subhead = Font.custom("Inter-Bold", size: 16)
        static let overline = Font.custom("Inter-Bold", size: 12)
        static let label01 = Font.custom("Inter-Bold", size: 12)
        static let label02 = Font.custom("Inter-Bold", size: 12)
        static let body = Font.custom("Inter-Medium", size: 14)
        static let caption = Font.custom("Inter-Regular", size: 12)
    }
}

extension Theme {
    enum LineHeight {
        static let display: CGFloat = 65
        static let h1: CGFloat = 53
        static let h2: CGFloat = 39
        static let h3: CGFloat = 29
        static let subhead: CGFloat = 19
        static let overline: CGFloat = 15
        static let label01: CGFloat = 15
        static let label02: CGFloat = 18
        static let body: CGFloat = 20
        static let caption: CGFloat = 15
    }
}
