// @generated by scripts/generate-tokens.js — DO NOT EDIT
import SwiftUI

extension Theme {
    enum Typography {
        static let display = Font.custom("Inter-Bold", size: 40)
        static let title1 = Font.custom("Inter-Bold", size: 28)
        static let title2 = Font.custom("Inter-SemiBold", size: 24)
        static let title3 = Font.custom("Inter-SemiBold", size: 20)
        static let headline = Font.custom("Inter-SemiBold", size: 18)
        static let body = Font.custom("Inter-Regular", size: 16)
        static let callout = Font.custom("Inter-Regular", size: 16)
        static let subheadline = Font.custom("Inter-Regular", size: 14)
        static let footnote = Font.custom("Inter-Regular", size: 14)
        static let caption1 = Font.custom("Inter-Regular", size: 12)
        static let caption2 = Font.custom("Inter-Regular", size: 12)
    }
}
