#!/usr/bin/env node
// Token pipeline: JSON → Swift code generation
// Zero-dependency Node.js script
// Usage: node scripts/generate-tokens.js

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const TOKENS = path.join(ROOT, 'tokens');
const DESIGN_SYSTEM = path.join(ROOT, 'ios', 'Pyramid', 'Sources', 'Shared', 'DesignSystem');

const GENERATED_HEADER = '// @generated by scripts/generate-tokens.js — DO NOT EDIT\n';

// ─── Load JSON inputs ────────────────────────────────────────────────────────

const palette = JSON.parse(fs.readFileSync(path.join(TOKENS, 'primitive', 'primitive.palette.json'), 'utf8'));
const sizing = JSON.parse(fs.readFileSync(path.join(TOKENS, 'primitive', 'primitive.sizing.json'), 'utf8'));
const semanticColor = JSON.parse(fs.readFileSync(path.join(TOKENS, 'semantic', 'semantic.color.json'), 'utf8'));
const semanticSpacing = JSON.parse(fs.readFileSync(path.join(TOKENS, 'semantic', 'semantic.spacing.json'), 'utf8'));
const semanticBorder = JSON.parse(fs.readFileSync(path.join(TOKENS, 'semantic', 'semantic.border.json'), 'utf8'));
const semanticTypography = JSON.parse(fs.readFileSync(path.join(TOKENS, 'semantic', 'semantic.typography.json'), 'utf8'));

// ─── Reference resolution ────────────────────────────────────────────────────

function resolvePaletteRef(ref) {
    // ref like "{palette.blue.50}" → palette.blue.50
    const match = ref.match(/^\{palette\.([^.]+)\.([^}]+)\}$/);
    if (!match) return ref;
    const [, colorName, shade] = match;
    return palette[colorName][shade];
}

function resolveSizingRef(ref) {
    // ref like "{sizing.30}" → sizing.scale.30
    const match = ref.match(/^\{sizing\.([^}]+)\}$/);
    if (!match) return ref;
    return sizing.scale[match[1]];
}

function isRgba(val) {
    return typeof val === 'string' && val.startsWith('rgba(');
}

function isHex(val) {
    return typeof val === 'string' && val.startsWith('#');
}

function stripHash(hex) {
    return hex.replace(/^#/, '');
}

function parseRgba(val) {
    // "rgba(32, 39, 59, 0.1)" → { r: 32, g: 39, b: 59, a: 0.1 }
    const match = val.match(/rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([0-9.]+)\s*\)/);
    if (!match) throw new Error(`Cannot parse rgba: ${val}`);
    return {
        r: parseInt(match[1]),
        g: parseInt(match[2]),
        b: parseInt(match[3]),
        a: parseFloat(match[4])
    };
}

// ─── Color output formatting ─────────────────────────────────────────────────

function formatColorValue(lightResolved, darkResolved, indent, lightRef, darkRef) {
    const lightIsHex = isHex(lightResolved);
    const darkIsHex = isHex(darkResolved);
    const lightIsRgba = isRgba(lightResolved);
    const darkIsRgba = isRgba(darkResolved);
    const innerIndent = indent + '    ';

    if (lightIsHex && darkIsHex) {
        const l = stripHash(lightResolved);
        const d = stripHash(darkResolved);
        // Only use solid() if the refs are identical (same token for both modes)
        if (l === d && lightRef === darkRef) {
            return `solid("${l}")`;
        }
        return `adaptive("${l}", "${d}")`;
    }

    if (lightIsRgba && darkIsRgba) {
        const l = parseRgba(lightResolved);
        const d = parseRgba(darkResolved);
        return `adaptiveUI(\n${innerIndent}light: rgba(${l.r}, ${l.g}, ${l.b}, ${l.a}), dark: rgba(${d.r}, ${d.g}, ${d.b}, ${d.a})\n${indent})`;
    }

    // Mixed: one hex, one rgba
    let lightPart, darkPart;
    if (lightIsHex) {
        lightPart = `Theme.hexToUIColor("${stripHash(lightResolved)}")`;
    } else {
        const l = parseRgba(lightResolved);
        lightPart = `rgba(${l.r}, ${l.g}, ${l.b}, ${l.a})`;
    }
    if (darkIsHex) {
        darkPart = `Theme.hexToUIColor("${stripHash(darkResolved)}")`;
    } else {
        const d = parseRgba(darkResolved);
        darkPart = `rgba(${d.r}, ${d.g}, ${d.b}, ${d.a})`;
    }
    return `adaptiveUI(\n${innerIndent}light: ${lightPart},\n${innerIndent}dark: ${darkPart}\n${indent})`;
}

function needsBacktick(name) {
    const reserved = ['default'];
    return reserved.includes(name);
}

function swiftName(name) {
    return needsBacktick(name) ? '`' + name + '`' : name;
}

// ─── Generate ThemeColors.swift ──────────────────────────────────────────────

function generateColorToken(name, lightRef, darkRef, indent) {
    const lightResolved = resolvePaletteRef(lightRef);
    const darkResolved = resolvePaletteRef(darkRef);
    // Pass original refs so we can distinguish same-value-different-ref from truly identical
    const formatted = formatColorValue(lightResolved, darkResolved, indent, lightRef, darkRef);
    return `${indent}static let ${swiftName(name)} = ${formatted}`;
}

function generateStatusEnum(statusName, tokens, subtleValue, indent) {
    const lines = [];
    lines.push(`${indent}enum ${capitalize(statusName)} {`);
    const innerIndent = indent + '    ';

    const tokenOrder = ['resting', 'pressed', 'text', 'disabled', 'border'];
    for (const tokenName of tokenOrder) {
        if (tokens[tokenName]) {
            const light = tokens[tokenName].light.value;
            const dark = tokens[tokenName].dark.value;
            lines.push(generateColorToken(tokenName, light, dark, innerIndent));
        }
    }

    if (subtleValue) {
        lines.push(`${innerIndent}static let subtle = ${subtleValue}`);
    }

    lines.push(`${indent}}`);
    return lines.join('\n');
}

function capitalize(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
}

function generateThemeColors() {
    const lines = [];
    lines.push(GENERATED_HEADER + 'import SwiftUI');
    lines.push('');
    lines.push('private func adaptive(_ light: String, _ dark: String) -> SwiftUI.Color {');
    lines.push('    Theme.color(light: light, dark: dark)');
    lines.push('}');
    lines.push('');
    lines.push('private func solid(_ hex: String) -> SwiftUI.Color {');
    lines.push('    Theme.color(light: hex, dark: hex)');
    lines.push('}');
    lines.push('');
    lines.push('private func adaptiveUI(');
    lines.push('    light: UIColor, dark: UIColor');
    lines.push(') -> SwiftUI.Color {');
    lines.push('    Theme.color(light: light, dark: dark)');
    lines.push('}');
    lines.push('');
    lines.push('private func rgba(');
    lines.push('    _ red: CGFloat, _ green: CGFloat, _ blue: CGFloat, _ alpha: CGFloat');
    lines.push(') -> UIColor {');
    lines.push('    Theme.rgbaUIColor(red, green, blue, alpha)');
    lines.push('}');
    lines.push('');
    lines.push('// MARK: - Theme.Color — Semantic color tokens');
    lines.push('');
    lines.push('extension Theme {');
    lines.push('    enum Color {');

    const indent8 = '        ';
    const indent12 = '            ';

    // Primary
    lines.push(`${indent8}enum Primary {`);
    const primaryTokens = semanticColor.primary;
    for (const name of ['resting', 'pressed', 'selected', 'text', 'disabled']) {
        lines.push(generateColorToken(name, primaryTokens[name].light.value, primaryTokens[name].dark.value, indent12));
    }
    lines.push(`${indent8}}`);

    // Secondary
    lines.push(`${indent8}enum Secondary {`);
    const secondaryTokens = semanticColor.secondary;
    for (const name of ['resting', 'pressed', 'selected', 'text', 'disabled']) {
        lines.push(generateColorToken(name, secondaryTokens[name].light.value, secondaryTokens[name].dark.value, indent12));
    }
    lines.push(`${indent8}}`);

    // Content
    lines.push(`${indent8}enum Content {`);

    // Content.Text
    lines.push(`${indent12}enum Text {`);
    const indent16 = '                ';
    const contentText = semanticColor.content.text;
    for (const name of ['default', 'subtle', 'contrast', 'disabled']) {
        lines.push(generateColorToken(name, contentText[name].light.value, contentText[name].dark.value, indent16));
    }
    lines.push(`${indent12}}`);

    // Content.Link
    lines.push(`${indent12}enum Link {`);
    const contentLink = semanticColor.content.link;
    for (const name of ['resting', 'pressed', 'contrast', 'disabled']) {
        lines.push(generateColorToken(name, contentLink[name].light.value, contentLink[name].dark.value, indent16));
    }
    lines.push(`${indent12}}`);

    lines.push(`${indent8}}`);

    // Surface
    lines.push(`${indent8}enum Surface {`);

    // Surface.Background
    lines.push(`${indent12}enum Background {`);
    const surfaceBg = semanticColor.surface.background;
    for (const name of ['container', 'highlight', 'page', 'disabled', 'transparent']) {
        lines.push(generateColorToken(name, surfaceBg[name].light.value, surfaceBg[name].dark.value, indent16));
    }
    lines.push(`${indent12}}`);

    // Surface.Overlay
    lines.push(`${indent12}enum Overlay {`);
    const surfaceOverlay = semanticColor.surface.overlay;
    for (const name of ['default', 'heavy']) {
        lines.push(generateColorToken(name, surfaceOverlay[name].light.value, surfaceOverlay[name].dark.value, indent16));
    }
    lines.push(`${indent12}}`);

    // Surface.Skeleton
    lines.push(`${indent12}enum Skeleton {`);
    const surfaceSkeleton = semanticColor.surface.skeleton;
    for (const name of ['default', 'heavy']) {
        lines.push(generateColorToken(name, surfaceSkeleton[name].light.value, surfaceSkeleton[name].dark.value, indent16));
    }
    lines.push(`${indent12}}`);

    lines.push(`${indent8}}`);

    // Border
    lines.push(`${indent8}enum Border {`);
    const borderTokens = semanticColor.border;
    for (const name of ['default', 'heavy']) {
        lines.push(generateColorToken(name, borderTokens[name].light.value, borderTokens[name].dark.value, indent12));
    }
    lines.push(`${indent8}}`);

    // Status
    // Subtle values use indent16 + 4 for inner content
    const subtleIndent = '                ';
    const subtleInner = '                    ';
    const subtleValues = {
        info: `adaptiveUI(\n${subtleInner}light: Theme.hexToUIColor("CFFAFE"),\n${subtleInner}dark: rgba(91, 111, 211, 0.15)\n${subtleIndent})`,
        error: `adaptiveUI(\n${subtleInner}light: Theme.hexToUIColor("FEE2E2"),\n${subtleInner}dark: rgba(255, 73, 75, 0.15)\n${subtleIndent})`,
        success: `adaptiveUI(\n${subtleInner}light: Theme.hexToUIColor("DCFCE7"),\n${subtleInner}dark: rgba(86, 204, 138, 0.15)\n${subtleIndent})`,
        warning: `adaptiveUI(\n${subtleInner}light: Theme.hexToUIColor("FEF3C7"),\n${subtleInner}dark: rgba(230, 126, 35, 0.15)\n${subtleIndent})`,
    };

    lines.push(`${indent8}enum Status {`);
    for (const statusName of ['info', 'error', 'success', 'warning', 'breaking']) {
        lines.push(generateStatusEnum(statusName, semanticColor.status[statusName], subtleValues[statusName] || null, indent12));
    }
    lines.push(`${indent8}}`);

    lines.push('    }');
    lines.push('}');

    return lines.join('\n') + '\n';
}

// ─── Generate ThemeSpacing.swift ─────────────────────────────────────────────

function generateThemeSpacing() {
    const lines = [];
    lines.push(GENERATED_HEADER + 'import SwiftUI');
    lines.push('');
    lines.push('extension Theme {');
    lines.push('    enum Spacing {');

    // Spacing: s0 through s130 from semantic.spacing.json → default variant → resolve sizing ref
    const spaceKeys = ['0', '10', '20', '30', '40', '50', '60', '70', '80', '90', '100', '110', '120', '130'];
    for (const key of spaceKeys) {
        const ref = semanticSpacing.space[key].default.value;
        const value = resolveSizingRef(ref);
        lines.push(`        static let s${key}: CGFloat = ${value}`);
    }

    lines.push('    }');
    lines.push('}');
    lines.push('');
    lines.push('extension Theme {');
    lines.push('    enum Radius {');

    // Radius: none (0), r05, r10, r20, r30, r40, r45, r50, r60, then default, pill, full
    const radiusNumericKeys = ['0', '05', '10', '20', '30', '40', '45', '50', '60'];
    const radiusNameMap = {
        '0': 'none',
    };

    for (const key of radiusNumericKeys) {
        const ref = semanticBorder.radius[key].value;
        const value = resolveSizingRef(ref);
        const name = radiusNameMap[key] || `r${key}`;
        lines.push(`        static let ${name}: CGFloat = ${value}`);
    }

    // Special named radii
    const defaultRef = semanticBorder.radius.default.value;
    const pillRef = semanticBorder.radius.pill.value;
    const fullRef = semanticBorder.radius.full.value;
    lines.push(`        static let \`default\`: CGFloat = ${resolveSizingRef(defaultRef)}`);
    lines.push(`        static let pill: CGFloat = ${resolveSizingRef(pillRef)}`);
    lines.push(`        static let full: CGFloat = ${resolveSizingRef(fullRef)}`);

    lines.push('    }');
    lines.push('}');
    lines.push('');

    // Shadow — hardcoded (not from JSON)
    lines.push('extension Theme {');
    lines.push('    enum Shadow {');
    lines.push('        struct Style {');
    lines.push('            let color: SwiftUI.Color');
    lines.push('            let radius: CGFloat');
    lines.push('            let x: CGFloat');
    lines.push('            let y: CGFloat');
    lines.push('        }');
    lines.push('        static let sm = Style(color: .black.opacity(0.06), radius: 2, x: 0, y: 1)');
    lines.push('        static let md = Style(color: .black.opacity(0.10), radius: 8, x: 0, y: 2)');
    lines.push('        static let lg = Style(color: .black.opacity(0.12), radius: 16, x: 0, y: 4)');
    lines.push('    }');
    lines.push('}');
    lines.push('');
    lines.push('extension View {');
    lines.push('    func themeShadow(_ style: Theme.Shadow.Style) -> some View {');
    lines.push('        self.shadow(color: style.color, radius: style.radius, x: style.x, y: style.y)');
    lines.push('    }');
    lines.push('}');

    return lines.join('\n') + '\n';
}

// ─── Generate ThemeTypography.swift ──────────────────────────────────────────

function generateThemeTypography() {
    const fontWeightMap = {
        'Thin': '.thin',
        'Extra Light': '.ultraLight',
        'Light': '.light',
        'Regular': '.regular',
        'Medium': '.medium',
        'Semi Bold': '.semibold',
        'Bold': '.bold',
        'Extra Bold': '.heavy',
        'Black': '.black',
    };

    // Semantic name → { fontSizeKey, fontWeightKey }
    const typographyMap = [
        { name: 'display', fontSizeKey: '90', fontWeightKey: '70' },
        { name: 'title1', fontSizeKey: '70', fontWeightKey: '70' },
        { name: 'title2', fontSizeKey: '60', fontWeightKey: '60' },
        { name: 'title3', fontSizeKey: '50', fontWeightKey: '60' },
        { name: 'headline', fontSizeKey: '40', fontWeightKey: '60' },
        { name: 'body', fontSizeKey: '30', fontWeightKey: '40' },
        { name: 'callout', fontSizeKey: '30', fontWeightKey: '40' },
        { name: 'subheadline', fontSizeKey: '20', fontWeightKey: '40' },
        { name: 'footnote', fontSizeKey: '20', fontWeightKey: '40' },
        { name: 'caption1', fontSizeKey: '10', fontWeightKey: '40' },
        { name: 'caption2', fontSizeKey: '10', fontWeightKey: '40' },
    ];

    const lines = [];
    lines.push(GENERATED_HEADER + 'import SwiftUI');
    lines.push('');
    lines.push('extension Theme {');
    lines.push('    enum Typography {');

    for (const entry of typographyMap) {
        const fontSize = semanticTypography.fontSize[entry.fontSizeKey].value;
        const fontWeightName = semanticTypography.fontWeight[entry.fontWeightKey].value;
        const swiftWeight = fontWeightMap[fontWeightName];
        lines.push(`        static let ${entry.name} = Font.system(size: ${fontSize}, weight: ${swiftWeight})`);
    }

    lines.push('    }');
    lines.push('}');

    return lines.join('\n') + '\n';
}

// ─── Write output files ──────────────────────────────────────────────────────

function main() {
    const colorsOutput = generateThemeColors();
    const spacingOutput = generateThemeSpacing();
    const typographyOutput = generateThemeTypography();

    fs.writeFileSync(path.join(DESIGN_SYSTEM, 'ThemeColors.swift'), colorsOutput, 'utf8');
    fs.writeFileSync(path.join(DESIGN_SYSTEM, 'ThemeSpacing.swift'), spacingOutput, 'utf8');
    fs.writeFileSync(path.join(DESIGN_SYSTEM, 'ThemeTypography.swift'), typographyOutput, 'utf8');

    console.log('Generated:');
    console.log('  - ThemeColors.swift');
    console.log('  - ThemeSpacing.swift');
    console.log('  - ThemeTypography.swift');
}

main();
