#!/usr/bin/env node
// Token pipeline: Figma Variables API → Swift code generation
// Source of truth: Figma file D0hIZP7fHnn37d8EfXGJoM (Core — Theme)
//
// Usage:
//   FIGMA_TOKEN=figd_... node scripts/generate-tokens.js
//   node scripts/generate-tokens.js --from-cache   (use local JSON files, no API call)
//
// Zero external dependencies. Uses native https + fs only.

const fs = require('fs');
const path = require('path');
const { fetchTokens } = require('./figma-token-fetcher');

const ROOT = path.resolve(__dirname, '..');
const TOKENS = path.join(ROOT, 'tokens');
const DESIGN_SYSTEM = path.join(ROOT, 'ios', 'Pyramid', 'Sources', 'Shared', 'DesignSystem');

const GENERATED_HEADER = '// @generated by scripts/generate-tokens.js from Figma — DO NOT EDIT\n';

// ─── Tokens missing from Figma but used in the codebase ────────────────────
// These are injected as fallbacks until they are added back to the Figma file.
// Tracked in: PYR-213 — remove once Figma has these variables.

const MISSING_TOKEN_FALLBACKS = {
    content: {
        text: {
            contrast: {
                light: { value: '#FFFFFF', type: 'color' },
                dark: { value: '#20273B', type: 'color' },
            },
        },
        link: {
            contrast: {
                light: { value: '#FFFFFF', type: 'color' },
                dark: { value: '#FFFFFF', type: 'color' },
            },
        },
    },
    surface: {
        background: {
            elevated: {
                light: { value: '#FFFFFF', type: 'color' },
                dark: { value: '#3D3354', type: 'color' },
            },
        },
    },
};

function deepMerge(target, source) {
    for (const [key, val] of Object.entries(source)) {
        if (val && typeof val === 'object' && val.value === undefined) {
            if (!target[key]) target[key] = {};
            deepMerge(target[key], val);
        } else if (!target[key]) {
            target[key] = val;
        }
    }
}

// ─── Load from cache (offline fallback) ─────────────────────────────────────

function loadFromCache() {
    const palette = JSON.parse(fs.readFileSync(path.join(TOKENS, 'primitive', 'primitive.palette.json'), 'utf8'));
    const sizing = JSON.parse(fs.readFileSync(path.join(TOKENS, 'primitive', 'primitive.sizing.json'), 'utf8'));
    const semanticColor = JSON.parse(fs.readFileSync(path.join(TOKENS, 'semantic', 'semantic.color.json'), 'utf8'));
    const semanticSpacing = JSON.parse(fs.readFileSync(path.join(TOKENS, 'semantic', 'semantic.spacing.json'), 'utf8'));
    const semanticBorder = JSON.parse(fs.readFileSync(path.join(TOKENS, 'semantic', 'semantic.border.json'), 'utf8'));

    function resolvePaletteRef(ref) {
        const match = ref.match(/^\{palette\.([^.]+)\.([^}]+)\}$/);
        if (!match) return ref;
        const [, colorName, shade] = match;
        if (!palette[colorName] || palette[colorName][shade] === undefined) {
            throw new Error(`Palette ref not found: ${ref} — check primitive.palette.json is current`);
        }
        return palette[colorName][shade];
    }

    function resolveColorTree(obj) {
        if (obj && obj.light && obj.dark && obj.light.value && obj.dark.value) {
            return {
                light: { value: resolvePaletteRef(obj.light.value), type: 'color' },
                dark: { value: resolvePaletteRef(obj.dark.value), type: 'color' },
            };
        }
        const result = {};
        for (const [k, v] of Object.entries(obj)) {
            result[k] = typeof v === 'object' ? resolveColorTree(v) : v;
        }
        return result;
    }

    function resolveSizingRef(ref) {
        const match = ref.match(/^\{sizing\.([^}]+)\}$/);
        if (!match) return ref;
        return sizing.scale[match[1]];
    }

    const resolvedSpacing = { space: {} };
    for (const [k, v] of Object.entries(semanticSpacing.space)) {
        resolvedSpacing.space[k] = { default: { value: resolveSizingRef(v.default.value) } };
    }

    const resolvedBorders = { radius: {} };
    for (const [k, v] of Object.entries(semanticBorder.radius)) {
        resolvedBorders.radius[k] = { value: resolveSizingRef(v.value) };
    }

    return {
        palette,
        semanticColor: resolveColorTree(semanticColor),
        spacing: resolvedSpacing,
        borders: resolvedBorders,
    };
}

// ─── Color output formatting ────────────────────────────────────────────────

function isRgba(val) {
    return typeof val === 'string' && val.startsWith('rgba(');
}

function isHex(val) {
    return typeof val === 'string' && val.startsWith('#');
}

function stripHash(hex) {
    return hex.replace(/^#/, '');
}

function parseRgba(val) {
    const match = val.match(/rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([0-9.]+)\s*\)/);
    if (!match) throw new Error(`Cannot parse rgba: ${val}`);
    return {
        r: parseInt(match[1]),
        g: parseInt(match[2]),
        b: parseInt(match[3]),
        a: parseFloat(match[4])
    };
}

function formatColorValue(lightResolved, darkResolved, indent) {
    const lightIsHex = isHex(lightResolved);
    const darkIsHex = isHex(darkResolved);
    const lightIsRgba = isRgba(lightResolved);
    const darkIsRgba = isRgba(darkResolved);
    const innerIndent = indent + '    ';

    if (lightIsHex && darkIsHex) {
        const l = stripHash(lightResolved);
        const d = stripHash(darkResolved);
        if (l === d) {
            return `solid("${l}")`;
        }
        return `adaptive("${l}", "${d}")`;
    }

    if (lightIsRgba && darkIsRgba) {
        const l = parseRgba(lightResolved);
        const d = parseRgba(darkResolved);
        return `adaptiveUI(\n${innerIndent}light: rgba(${l.r}, ${l.g}, ${l.b}, ${l.a}), dark: rgba(${d.r}, ${d.g}, ${d.b}, ${d.a})\n${indent})`;
    }

    // Mixed: one hex, one rgba
    let lightPart, darkPart;
    if (lightIsHex) {
        lightPart = `Theme.hexToUIColor("${stripHash(lightResolved)}")`;
    } else {
        const l = parseRgba(lightResolved);
        lightPart = `rgba(${l.r}, ${l.g}, ${l.b}, ${l.a})`;
    }
    if (darkIsHex) {
        darkPart = `Theme.hexToUIColor("${stripHash(darkResolved)}")`;
    } else {
        const d = parseRgba(darkResolved);
        darkPart = `rgba(${d.r}, ${d.g}, ${d.b}, ${d.a})`;
    }
    return `adaptiveUI(\n${innerIndent}light: ${lightPart},\n${innerIndent}dark: ${darkPart}\n${indent})`;
}

function needsBacktick(name) {
    const reserved = ['default'];
    return reserved.includes(name);
}

function swiftName(name) {
    return needsBacktick(name) ? '`' + name + '`' : name;
}

function capitalize(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
}

// ─── Generate ThemeColors.swift ─────────────────────────────────────────────

function generateColorToken(name, lightVal, darkVal, indent) {
    const formatted = formatColorValue(lightVal, darkVal, indent);
    return `${indent}static let ${swiftName(name)} = ${formatted}`;
}

function generateStatusEnum(statusName, tokens, subtleValue, indent) {
    const lines = [];
    lines.push(`${indent}enum ${capitalize(statusName)} {`);
    const innerIndent = indent + '    ';

    const tokenOrder = ['resting', 'pressed', 'text', 'disabled', 'border'];
    for (const tokenName of tokenOrder) {
        if (tokens[tokenName]) {
            lines.push(generateColorToken(tokenName, tokens[tokenName].light.value, tokens[tokenName].dark.value, innerIndent));
        }
    }

    if (subtleValue) {
        lines.push(`${innerIndent}static let subtle = ${subtleValue}`);
    }

    lines.push(`${indent}}`);
    return lines.join('\n');
}

function generateThemeColors(semanticColor) {
    const lines = [];
    lines.push(GENERATED_HEADER + 'import SwiftUI');
    lines.push('');
    lines.push('private func adaptive(_ light: String, _ dark: String) -> SwiftUI.Color {');
    lines.push('    Theme.color(light: light, dark: dark)');
    lines.push('}');
    lines.push('');
    lines.push('private func solid(_ hex: String) -> SwiftUI.Color {');
    lines.push('    Theme.color(light: hex, dark: hex)');
    lines.push('}');
    lines.push('');
    lines.push('private func adaptiveUI(');
    lines.push('    light: UIColor, dark: UIColor');
    lines.push(') -> SwiftUI.Color {');
    lines.push('    Theme.color(light: light, dark: dark)');
    lines.push('}');
    lines.push('');
    lines.push('private func rgba(');
    lines.push('    _ red: CGFloat, _ green: CGFloat, _ blue: CGFloat, _ alpha: CGFloat');
    lines.push(') -> UIColor {');
    lines.push('    Theme.rgbaUIColor(red, green, blue, alpha)');
    lines.push('}');
    lines.push('');
    lines.push('// MARK: - Theme.Color — Semantic color tokens');
    lines.push('');
    lines.push('extension Theme {');
    lines.push('    enum Color {');

    const indent8 = '        ';
    const indent12 = '            ';
    const indent16 = '                ';

    // Primary
    lines.push(`${indent8}enum Primary {`);
    for (const name of ['resting', 'pressed', 'selected', 'text', 'disabled']) {
        if (semanticColor.primary[name]) {
            lines.push(generateColorToken(name, semanticColor.primary[name].light.value, semanticColor.primary[name].dark.value, indent12));
        }
    }
    lines.push(`${indent8}}`);

    // Secondary
    lines.push(`${indent8}enum Secondary {`);
    for (const name of ['resting', 'pressed', 'selected', 'text', 'disabled']) {
        if (semanticColor.secondary[name]) {
            lines.push(generateColorToken(name, semanticColor.secondary[name].light.value, semanticColor.secondary[name].dark.value, indent12));
        }
    }
    lines.push(`${indent8}}`);

    // Content
    lines.push(`${indent8}enum Content {`);

    lines.push(`${indent12}enum Text {`);
    const contentText = semanticColor.content?.text ?? {};
    for (const name of ['default', 'subtle', 'contrast', 'disabled']) {
        if (contentText[name]) {
            lines.push(generateColorToken(name, contentText[name].light.value, contentText[name].dark.value, indent16));
        }
    }
    lines.push(`${indent12}}`);

    lines.push(`${indent12}enum Link {`);
    const contentLink = semanticColor.content?.link ?? {};
    for (const name of ['resting', 'pressed', 'contrast', 'disabled']) {
        if (contentLink[name]) {
            lines.push(generateColorToken(name, contentLink[name].light.value, contentLink[name].dark.value, indent16));
        }
    }
    lines.push(`${indent12}}`);

    lines.push(`${indent8}}`);

    // Surface
    lines.push(`${indent8}enum Surface {`);

    lines.push(`${indent12}enum Background {`);
    const surfaceBg = semanticColor.surface?.background ?? {};
    for (const name of ['container', 'elevated', 'highlight', 'page', 'disabled', 'transparent']) {
        if (surfaceBg[name]) {
            lines.push(generateColorToken(name, surfaceBg[name].light.value, surfaceBg[name].dark.value, indent16));
        }
    }
    lines.push(`${indent12}}`);

    lines.push(`${indent12}enum Overlay {`);
    const surfaceOverlay = semanticColor.surface?.overlay ?? {};
    for (const name of ['default', 'heavy']) {
        if (surfaceOverlay[name]) {
            lines.push(generateColorToken(name, surfaceOverlay[name].light.value, surfaceOverlay[name].dark.value, indent16));
        }
    }
    lines.push(`${indent12}}`);

    lines.push(`${indent12}enum Skeleton {`);
    const surfaceSkeleton = semanticColor.surface?.skeleton ?? {};
    for (const name of ['default', 'heavy']) {
        if (surfaceSkeleton[name]) {
            lines.push(generateColorToken(name, surfaceSkeleton[name].light.value, surfaceSkeleton[name].dark.value, indent16));
        }
    }
    lines.push(`${indent12}}`);

    lines.push(`${indent8}}`);

    // Border
    lines.push(`${indent8}enum Border {`);
    const borderTokens = semanticColor.border;
    for (const name of ['default', 'heavy']) {
        if (borderTokens[name]) {
            lines.push(generateColorToken(name, borderTokens[name].light.value, borderTokens[name].dark.value, indent12));
        }
    }
    lines.push(`${indent8}}`);

    // Status
    const subtleIndent = '                ';
    const subtleInner = '                    ';
    const subtleValues = {
        info: `adaptiveUI(\n${subtleInner}light: Theme.hexToUIColor("CFFAFE"),\n${subtleInner}dark: rgba(91, 111, 211, 0.15)\n${subtleIndent})`,
        error: `adaptiveUI(\n${subtleInner}light: Theme.hexToUIColor("FEE2E2"),\n${subtleInner}dark: rgba(255, 73, 75, 0.15)\n${subtleIndent})`,
        success: `adaptiveUI(\n${subtleInner}light: Theme.hexToUIColor("DCFCE7"),\n${subtleInner}dark: rgba(86, 204, 138, 0.15)\n${subtleIndent})`,
        warning: `adaptiveUI(\n${subtleInner}light: Theme.hexToUIColor("FEF3C7"),\n${subtleInner}dark: rgba(230, 126, 35, 0.15)\n${subtleIndent})`,
    };

    lines.push(`${indent8}enum Status {`);
    for (const statusName of ['info', 'error', 'success', 'warning', 'breaking']) {
        if (semanticColor.status[statusName]) {
            lines.push(generateStatusEnum(statusName, semanticColor.status[statusName], subtleValues[statusName] || null, indent12));
        }
    }
    lines.push(`${indent8}}`);

    lines.push('    }');
    lines.push('}');

    return lines.join('\n') + '\n';
}

// ─── Generate ThemeSpacing.swift ────────────────────────────────────────────

function generateThemeSpacing(spacing, borders) {
    const lines = [];
    lines.push(GENERATED_HEADER + 'import SwiftUI');
    lines.push('');
    lines.push('extension Theme {');
    lines.push('    enum Spacing {');

    const spaceKeys = ['0', '10', '20', '30', '40', '50', '60', '70', '80', '90', '100', '110', '120', '130'];
    for (const key of spaceKeys) {
        if (spacing.space[key]) {
            const value = spacing.space[key].default.value;
            lines.push(`        static let s${key}: CGFloat = ${value}`);
        }
    }

    lines.push('    }');
    lines.push('}');
    lines.push('');
    lines.push('extension Theme {');
    lines.push('    enum Radius {');

    const radiusNumericKeys = ['0', '05', '10', '20', '30', '40', '45', '50', '60'];
    const radiusNameMap = { '0': 'none' };

    for (const key of radiusNumericKeys) {
        if (borders.radius[key]) {
            const value = borders.radius[key].value;
            const name = radiusNameMap[key] || `r${key}`;
            lines.push(`        static let ${name}: CGFloat = ${value}`);
        }
    }

    // Special named radii
    if (borders.radius.default) lines.push(`        static let \`default\`: CGFloat = ${borders.radius.default.value}`);
    if (borders.radius.pill) lines.push(`        static let pill: CGFloat = ${borders.radius.pill.value}`);
    if (borders.radius.full) lines.push(`        static let full: CGFloat = ${borders.radius.full.value}`);

    lines.push('    }');
    lines.push('}');
    lines.push('');

    // Shadow — hardcoded (not from Figma variables)
    lines.push('extension Theme {');
    lines.push('    enum Shadow {');
    lines.push('        struct Style {');
    lines.push('            let color: SwiftUI.Color');
    lines.push('            let radius: CGFloat');
    lines.push('            let x: CGFloat');
    lines.push('            let y: CGFloat');
    lines.push('        }');
    lines.push('        static let sm = Style(color: .black.opacity(0.06), radius: 2, x: 0, y: 1)');
    lines.push('        static let md = Style(color: .black.opacity(0.10), radius: 8, x: 0, y: 2)');
    lines.push('        static let lg = Style(color: .black.opacity(0.12), radius: 16, x: 0, y: 4)');
    lines.push('    }');
    lines.push('}');
    lines.push('');
    lines.push('extension View {');
    lines.push('    func themeShadow(_ style: Theme.Shadow.Style) -> some View {');
    lines.push('        self.shadow(color: style.color, radius: style.radius, x: style.x, y: style.y)');
    lines.push('    }');
    lines.push('}');
    lines.push('');

    // Gradient — from Figma design system
    lines.push('extension Theme {');
    lines.push('    enum Gradient {');
    lines.push('        static let primary = LinearGradient(');
    lines.push('            colors: [Theme.color(light: "5E4E80", dark: "5E4E80"), Theme.color(light: "2C253D", dark: "2C253D")],');
    lines.push('            startPoint: .top,');
    lines.push('            endPoint: .bottom');
    lines.push('        )');
    lines.push('    }');
    lines.push('}');

    return lines.join('\n') + '\n';
}

// ─── Generate ThemeTypography.swift ─────────────────────────────────────────
// Typography text styles are not available as Figma Variables (they're
// component-level styles, not primitive variables). These are sourced
// from tokens/semantic/semantic.typography.json until Figma adds
// text style variable support.

function generateThemeTypography(typography) {
    const interFontNameMap = {
        'Regular': 'Inter-Regular',
        'Medium': 'Inter-Medium',
        'Semi Bold': 'Inter-SemiBold',
        'Bold': 'Inter-Bold',
    };

    const textStyles = typography.textStyles;

    const lines = [];
    lines.push(GENERATED_HEADER + 'import SwiftUI');
    lines.push('');
    lines.push('// MARK: - Theme.Typography — Text styles from Figma');
    lines.push('');
    lines.push('extension Theme {');
    lines.push('    enum Typography {');

    for (const [name, style] of Object.entries(textStyles)) {
        const interName = interFontNameMap[style.fontWeight];
        if (!interName) {
            throw new Error(`No Inter font mapped for weight: ${style.fontWeight}`);
        }
        if (typeof style.fontSize !== 'number' || style.fontSize < 1 || style.fontSize > 200) {
            throw new Error(`Invalid fontSize ${style.fontSize} for style "${name}"`);
        }
        lines.push(`        static let ${name} = Font.custom("${interName}", size: ${style.fontSize})`);
    }

    lines.push('    }');
    lines.push('}');
    lines.push('');

    lines.push('extension Theme {');
    lines.push('    enum LineHeight {');

    for (const [name, style] of Object.entries(textStyles)) {
        lines.push(`        static let ${name}: CGFloat = ${style.lineHeight}`);
    }

    lines.push('    }');
    lines.push('}');

    return lines.join('\n') + '\n';
}

// ─── Main ───────────────────────────────────────────────────────────────────

async function main() {
    const fromCache = process.argv.includes('--from-cache');
    const typography = JSON.parse(fs.readFileSync(path.join(TOKENS, 'semantic', 'semantic.typography.json'), 'utf8'));

    let semanticColor, spacing, borders;

    if (fromCache) {
        console.log('Using cached JSON files (offline mode)');
        const cached = loadFromCache();
        semanticColor = cached.semanticColor;
        spacing = cached.spacing;
        borders = cached.borders;
    } else {
        const figmaToken = process.env.FIGMA_TOKEN;
        if (!figmaToken) {
            console.error('Error: FIGMA_TOKEN environment variable is required.');
            console.error('  Set it: export FIGMA_TOKEN=figd_...');
            console.error('  Or use: node scripts/generate-tokens.js --from-cache');
            process.exit(1);
        }
        console.log('Fetching tokens from Figma Variables API...');
        const data = await fetchTokens(figmaToken);
        semanticColor = data.semanticColor;
        spacing = data.spacing;
        borders = data.borders;
    }

    // Inject fallbacks for tokens missing from Figma (used in codebase)
    deepMerge(semanticColor, MISSING_TOKEN_FALLBACKS);

    const colorsOutput = generateThemeColors(semanticColor);
    const spacingOutput = generateThemeSpacing(spacing, borders);
    const typographyOutput = generateThemeTypography(typography);

    fs.writeFileSync(path.join(DESIGN_SYSTEM, 'ThemeColors.swift'), colorsOutput, 'utf8');
    fs.writeFileSync(path.join(DESIGN_SYSTEM, 'ThemeSpacing.swift'), spacingOutput, 'utf8');
    fs.writeFileSync(path.join(DESIGN_SYSTEM, 'ThemeTypography.swift'), typographyOutput, 'utf8');

    console.log('Generated:');
    console.log('  - ThemeColors.swift');
    console.log('  - ThemeSpacing.swift');
    console.log('  - ThemeTypography.swift');
    console.log(`Source: ${fromCache ? 'local JSON cache' : 'Figma Variables API'}`);
}

main().catch((err) => {
    console.error(err.message);
    process.exit(1);
});
