#!/usr/bin/env bash
set -euo pipefail

# Usage: post-snapshots.sh <manifest-path> <snapshots-dir> <pr-number> <matched-labels-json>

MANIFEST="$1"
SNAPSHOTS_DIR="$2"
PR_NUMBER="$3"
MATCHED_LABELS="$4"

REPO="${GITHUB_REPOSITORY:-}"
if [ -z "$REPO" ]; then
  echo "Error: GITHUB_REPOSITORY not set"
  exit 1
fi

# Delete any existing snapshot comment (identified by marker)
EXISTING=$(gh api "repos/${REPO}/issues/${PR_NUMBER}/comments" \
  --jq '.[] | select(.body | contains("<!-- snapshot-qa -->")) | .id' 2>/dev/null || true)

if [ -n "$EXISTING" ]; then
  gh api "repos/${REPO}/issues/comments/${EXISTING}" -X DELETE 2>/dev/null || true
fi

# Build comment body
BODY="<!-- snapshot-qa -->"$'\n'
BODY+="## 📸 Visual QA Snapshots"$'\n'
BODY+="Auto-generated from components changed in this PR"$'\n\n'

FOUND_IMAGES=false

while IFS= read -r label; do
  TEST_CLASS=$(jq -r --arg l "$label" \
    '.mappings[] | select(.label == $l) | .testClass' "$MANIFEST")

  SNAP_DIR="${SNAPSHOTS_DIR}/__Snapshots__/${TEST_CLASS}"

  if [ ! -d "$SNAP_DIR" ]; then
    continue
  fi

  BODY+="### ${label}"$'\n\n'
  BODY+="| Variant | Snapshot |"$'\n'
  BODY+="| :--- | :---: |"$'\n'

  for png in "$SNAP_DIR"/*.png; do
    [ -f "$png" ] || continue
    FOUND_IMAGES=true
    BASENAME=$(basename "$png" .png)
    BODY+="| \`${BASENAME}\` | *See artifacts* |"$'\n'
  done

  BODY+=$'\n'
done < <(echo "$MATCHED_LABELS" | jq -r '.[]')

if [ "$FOUND_IMAGES" = false ]; then
  echo "No snapshot images found — skipping PR comment"
  exit 0
fi

BODY+="---"$'\n'
BODY+="📎 [Download snapshots](../actions/runs/${GITHUB_RUN_ID:-})"
BODY+=" • iPhone 16 / iOS 18.2 • Generated by \`snapshot-pr.yml\`"

gh pr comment "$PR_NUMBER" --body "$BODY"

echo "✅ Snapshot comment posted to PR #${PR_NUMBER}"
