#!/usr/bin/env bash
set -euo pipefail

# Usage: post-snapshots.sh <manifest-path> <snapshots-dir> <pr-number> <matched-labels-json>

MANIFEST="$1"
SNAPSHOTS_DIR="$2"
PR_NUMBER="$3"
MATCHED_LABELS="$4"

REPO="${GITHUB_REPOSITORY:-}"
if [ -z "$REPO" ]; then
  echo "Error: GITHUB_REPOSITORY not set"
  exit 1
fi

# Delete any existing snapshot comment (identified by marker)
EXISTING=$(gh api "repos/${REPO}/issues/${PR_NUMBER}/comments" \
  --jq '.[] | select(.body | contains("<!-- snapshot-qa -->")) | .id' 2>/dev/null || true)

if [ -n "$EXISTING" ]; then
  gh api "repos/${REPO}/issues/comments/${EXISTING}" -X DELETE 2>/dev/null || true
fi

# Upload a PNG to GitHub via the camo/image upload endpoint and return the URL.
# Uses the same mechanism as drag-and-drop images in GitHub comments.
upload_image() {
  local file="$1"
  local filename
  filename=$(basename "$file")

  # Upload via GitHub's attachment API
  local response
  response=$(curl -s -X POST \
    "https://uploads.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments" \
    -H "Authorization: token ${GH_TOKEN}" \
    -H "Content-Type: image/png" \
    -H "Content-Length: $(wc -c < "$file")" \
    --data-binary "@${file}" 2>/dev/null || echo "")

  # Fallback: commit image to a snapshot branch and use raw URL
  local SNAP_BRANCH="snapshots/pr-${PR_NUMBER}"
  local SNAP_PATH="snapshots/${filename}"

  # Base64 encode the image
  local CONTENT
  CONTENT=$(base64 -i "$file")

  # Check if file already exists on this branch
  local SHA=""
  SHA=$(gh api "repos/${REPO}/contents/${SNAP_PATH}?ref=${SNAP_BRANCH}" \
    --jq '.sha' 2>/dev/null || echo "")

  local PUT_BODY
  if [ -n "$SHA" ]; then
    PUT_BODY=$(jq -n --arg msg "snapshot: ${filename}" \
      --arg content "$CONTENT" \
      --arg branch "$SNAP_BRANCH" \
      --arg sha "$SHA" \
      '{message: $msg, content: $content, branch: $branch, sha: $sha}')
  else
    # Ensure branch exists (create from default branch if needed)
    gh api "repos/${REPO}/git/refs" \
      -X POST \
      -f "ref=refs/heads/${SNAP_BRANCH}" \
      -f "sha=$(gh api repos/${REPO}/git/ref/heads/main --jq '.object.sha')" \
      2>/dev/null || true

    PUT_BODY=$(jq -n --arg msg "snapshot: ${filename}" \
      --arg content "$CONTENT" \
      --arg branch "$SNAP_BRANCH" \
      '{message: $msg, content: $content, branch: $branch}')
  fi

  local UPLOAD_RESULT
  UPLOAD_RESULT=$(gh api "repos/${REPO}/contents/${SNAP_PATH}" \
    -X PUT \
    --input - <<< "$PUT_BODY" 2>/dev/null || echo "")

  local RAW_URL
  RAW_URL=$(echo "$UPLOAD_RESULT" | jq -r '.content.download_url // empty')

  if [ -n "$RAW_URL" ]; then
    echo "$RAW_URL"
  else
    echo ""
  fi
}

# Build comment body
BODY="<!-- snapshot-qa -->"$'\n'
BODY+="## Visual QA Snapshots"$'\n'
BODY+="Auto-generated from components changed in this PR."$'\n\n'

FOUND_IMAGES=false

while IFS= read -r label; do
  TEST_CLASS=$(jq -r --arg l "$label" \
    '.mappings[] | select(.label == $l) | .testClass' "$MANIFEST")

  SNAP_DIR="${SNAPSHOTS_DIR}/__Snapshots__/${TEST_CLASS}"

  if [ ! -d "$SNAP_DIR" ]; then
    continue
  fi

  BODY+="### ${label}"$'\n\n'

  for png in "$SNAP_DIR"/*.png; do
    [ -f "$png" ] || continue
    FOUND_IMAGES=true
    BASENAME=$(basename "$png" .png)

    echo "Uploading ${BASENAME}.png ..."
    IMG_URL=$(upload_image "$png")

    if [ -n "$IMG_URL" ]; then
      BODY+="**\`${BASENAME}\`**"$'\n\n'
      BODY+="![${BASENAME}](${IMG_URL})"$'\n\n'
    else
      BODY+="**\`${BASENAME}\`** — upload failed, see artifacts"$'\n\n'
    fi
  done

done < <(echo "$MATCHED_LABELS" | jq -r '.[]')

if [ "$FOUND_IMAGES" = false ]; then
  echo "No snapshot images found — skipping PR comment"
  exit 0
fi

BODY+="---"$'\n'
BODY+="iPhone 16 / iOS 18.2 | Generated by \`snapshot-pr.yml\`"

gh pr comment "$PR_NUMBER" --body "$BODY"

echo "Snapshot comment posted to PR #${PR_NUMBER}"
