#!/usr/bin/env bash
set -euo pipefail

# Usage: post-snapshots.sh <manifest-path> <snapshots-dir> <pr-number> <matched-labels-json>

MANIFEST="$1"
SNAPSHOTS_DIR="$2"
PR_NUMBER="$3"
MATCHED_LABELS="$4"

REPO="${GITHUB_REPOSITORY:-}"
if [ -z "$REPO" ]; then
  echo "Error: GITHUB_REPOSITORY not set"
  exit 1
fi

SNAP_BRANCH="snapshots/pr-${PR_NUMBER}"

# Delete any existing snapshot comment (identified by marker)
EXISTING=$(gh api "repos/${REPO}/issues/${PR_NUMBER}/comments" \
  --jq '.[] | select(.body | contains("<!-- snapshot-qa -->")) | .id' 2>/dev/null || true)

if [ -n "$EXISTING" ]; then
  gh api "repos/${REPO}/issues/comments/${EXISTING}" -X DELETE 2>/dev/null || true
fi

# Ensure snapshot branch exists
ensure_branch() {
  if ! gh api "repos/${REPO}/git/ref/heads/${SNAP_BRANCH}" >/dev/null 2>&1; then
    echo "Creating snapshot branch ${SNAP_BRANCH}..."
    local MAIN_SHA
    MAIN_SHA=$(gh api "repos/${REPO}/git/ref/heads/main" --jq '.object.sha')
    gh api "repos/${REPO}/git/refs" \
      -X POST \
      -f "ref=refs/heads/${SNAP_BRANCH}" \
      -f "sha=${MAIN_SHA}" || {
        echo "ERROR: Failed to create branch ${SNAP_BRANCH}"
        return 1
      }
  fi
}

# Upload a PNG to the snapshot branch via Contents API
upload_image() {
  local file="$1"
  local filename
  filename=$(basename "$file")
  local filepath="snapshots/${filename}"

  local CONTENT
  CONTENT=$(base64 -i "$file")

  # Check if file exists (to get SHA for update)
  local SHA=""
  SHA=$(gh api "repos/${REPO}/contents/${filepath}?ref=${SNAP_BRANCH}" \
    --jq '.sha' 2>/dev/null || echo "")

  local RESULT
  if [ -n "$SHA" ]; then
    RESULT=$(gh api "repos/${REPO}/contents/${filepath}" \
      -X PUT \
      -f "message=snapshot: ${filename}" \
      -f "content=${CONTENT}" \
      -f "branch=${SNAP_BRANCH}" \
      -f "sha=${SHA}" 2>&1) || {
        echo "ERROR uploading ${filename} (update): ${RESULT}"
        return 1
      }
  else
    RESULT=$(gh api "repos/${REPO}/contents/${filepath}" \
      -X PUT \
      -f "message=snapshot: ${filename}" \
      -f "content=${CONTENT}" \
      -f "branch=${SNAP_BRANCH}" 2>&1) || {
        echo "ERROR uploading ${filename} (create): ${RESULT}"
        return 1
      }
  fi

  # Extract raw URL
  local RAW_URL
  RAW_URL=$(echo "$RESULT" | jq -r '.content.download_url // empty')
  echo "$RAW_URL"
}

# Build comment body
BODY="<!-- snapshot-qa -->"$'\n'
BODY+="## Visual QA Snapshots"$'\n'
BODY+="Auto-generated from components changed in this PR."$'\n\n'

FOUND_IMAGES=false
BRANCH_CREATED=false

while IFS= read -r label; do
  TEST_CLASS=$(jq -r --arg l "$label" \
    '.mappings[] | select(.label == $l) | .testClass' "$MANIFEST")

  SNAP_DIR="${SNAPSHOTS_DIR}/__Snapshots__/${TEST_CLASS}"

  if [ ! -d "$SNAP_DIR" ]; then
    echo "Directory not found: ${SNAP_DIR}"
    continue
  fi

  # Create branch on first image found
  if [ "$BRANCH_CREATED" = false ]; then
    ensure_branch || {
      echo "Failed to create snapshot branch, falling back to artifact links"
      break
    }
    BRANCH_CREATED=true
  fi

  BODY+="### ${label}"$'\n\n'

  for png in "$SNAP_DIR"/*.png; do
    [ -f "$png" ] || continue
    FOUND_IMAGES=true
    BASENAME=$(basename "$png" .png)

    echo "Uploading ${BASENAME}.png ..."
    IMG_URL=$(upload_image "$png") || IMG_URL=""

    if [ -n "$IMG_URL" ]; then
      echo "  -> ${IMG_URL}"
      BODY+="**\`${BASENAME}\`**"$'\n\n'
      BODY+="<img src=\"${IMG_URL}\" width=\"345\" />"$'\n\n'
    else
      echo "  -> FAILED"
      BODY+="**\`${BASENAME}\`** — upload failed, see artifacts"$'\n\n'
    fi
  done

done < <(echo "$MATCHED_LABELS" | jq -r '.[]')

if [ "$FOUND_IMAGES" = false ]; then
  echo "No snapshot images found — skipping PR comment"
  exit 0
fi

BODY+="---"$'\n'
BODY+="iPhone 16 / iOS 18.2 | Generated by \`snapshot-pr.yml\`"

gh pr comment "$PR_NUMBER" --body "$BODY"

echo "Snapshot comment posted to PR #${PR_NUMBER}"
